const flexStyles = {
	alignContent: ['flex-start', 'flex-end', 'center', 'stretch', 'space-between', 'space-around', 'space-evenly'],
	alignItems: ['flex-start', 'flex-end', 'center', 'stretch', 'baseline'],
	alignSelf: ['auto', 'flex-start', 'flex-end', 'center', 'stretch', 'baseline'],
	aspectRatio: 'number',
	borderBottomWidth: 'number',
	borderEndWidth: 'number',
	borderLeftWidth: 'number',
	borderRightWidth: 'number',
	borderStartWidth: 'number',
	borderTopWidth: 'number',
	borderWidth: 'number',
	bottom: ['number', 'string'],
	columnGap: 'number',
	direction: ['inherit', 'ltr', 'rtl'],
	display: ['flex', 'none'],
	end: ['number', 'string'],
	flex: 'number',
	flexBasis: ['number', 'string'],
	flexDirection: ['row', 'row-reverse', 'column', 'column-reverse'],
	flexGrow: 'number',
	flexShrink: 'number',
	flexWrap: ['wrap', 'nowrap', 'wrap-reverse'],
	gap: 'number',
	height: ['number', 'string'],
	inset: ['number', 'string'],
	insetBlock: ['number', 'string'],
	insetBlockEnd: ['number', 'string'],
	insetBlockStart: ['number', 'string'],
	insetInline: ['number', 'string'],
	insetInlineEnd: ['number', 'string'],
	insetInlineStart: ['number', 'string'],
	justifyContent: ['flex-start', 'flex-end', 'center', 'space-between', 'space-around', 'space-evenly'],
	left: ['number', 'string'],
	margin: ['number', 'string'],
	marginBlock: ['number', 'string'],
	marginBlockEnd: ['number', 'string'],
	marginBlockStart: ['number', 'string'],
	marginBottom: ['number', 'string'],
	marginEnd: ['number', 'string'],
	marginHorizontal: ['number', 'string'],
	marginInline: ['number', 'string'],
	marginInlineEnd: ['number', 'string'],
	marginInlineStart: ['number', 'string'],
	marginLeft: ['number', 'string'],
	marginRight: ['number', 'string'],
	marginStart: ['number', 'string'],
	marginTop: ['number', 'string'],
	marginVertical: ['number', 'string'],
	maxHeight: ['number', 'string'],
	maxWidth: ['number', 'string'],
	minHeight: ['number', 'string'],
	minWidth: ['number', 'string'],
	overflow: ['visible', 'hidden', 'scroll'],
	padding: ['number', 'string'],
	paddingBlock: ['number', 'string'],
	paddingBlockEnd: ['number', 'string'],
	paddingBlockStart: ['number', 'string'],
	paddingBottom: ['number', 'string'],
	paddingEnd: ['number', 'string'],
	paddingHorizontal: ['number', 'string'],
	paddingInline: ['number', 'string'],
	paddingInlineEnd: ['number', 'string'],
	paddingInlineStart: ['number', 'string'],
	paddingLeft: ['number', 'string'],
	paddingRight: ['number', 'string'],
	paddingStart: ['number', 'string'],
	paddingTop: ['number', 'string'],
	paddingVertical: ['number', 'string'],
	position: ['absolute', 'relative'],
	right: ['number', 'string'],
	rowGap: 'number',
	start: ['number', 'string'],
	top: ['number', 'string'],
	width: ['number', 'string'],
	zIndex: 'number',
	shadowColor: 'string',
	shadowOffset: { width: 'number', height: 'number' },
	shadowOpacity: 'number',
	shadowRadius: 'number',
	transform: 'TransformStyle',
	backfaceVisibility: ['visible', 'hidden'],
	backgroundColor: 'string',
	borderBottomColor: 'string',
	borderBottomEndRadius: ['number', 'string'],
	borderBottomLeftRadius: ['number', 'string'],
	borderBottomRightRadius: ['number', 'string'],
	borderBottomStartRadius: ['number', 'string'],
	borderColor: 'string',
	borderCurve: 'number',
	borderEndColor: 'string',
	borderEndEndRadius: ['number', 'string'],
	borderEndStartRadius: ['number', 'string'],
	borderLeftColor: 'string',
	borderRadius: ['number', 'string'],
	borderRightColor: 'string',
	borderStartColor: 'string',
	borderStartEndRadius: ['number', 'string'],
	borderStartStartRadius: ['number', 'string'],
	borderStyle: ['solid', 'dotted', 'dashed'],
	borderTopColor: 'string',
	borderTopEndRadius: ['number', 'string'],
	borderTopLeftRadius: ['number', 'string'],
	borderTopRightRadius: ['number', 'string'],
	borderTopStartRadius: ['number', 'string'],
	elevation: 'number',
	opacity: 'number',
	pointerEvents: ['auto', 'none'],
	color: 'string',
	fontFamily: 'string',
	fontSize: 'number',
	fontStyle: ['normal', 'italic'],
	fontVariant: ['small-caps', 'normal'],
	fontWeight: ['normal', 'bold', '100', '200', '300', '400', '500', '600', '700', '800', '900'],
	includeFontPadding: 'boolean',
	letterSpacing: 'number',
	lineHeight: 'number',
	textAlign: ['auto', 'left', 'right', 'center', 'justify'],
	textAlignVertical: ['auto', 'top', 'bottom', 'center'],
	textDecorationColor: 'string',
	textDecorationLine: ['none', 'underline', 'line-through', 'underline line-through'],
	textDecorationStyle: ['solid', 'double', 'dotted', 'dashed'],
	textShadowColor: 'string',
	textShadowOffset: { width: 'number', height: 'number' },
	textShadowRadius: 'number',
	textTransform: ['none', 'capitalize', 'uppercase', 'lowercase'],
	userSelect: ['auto', 'none', 'text', 'contain', 'all'],
	verticalAlign: ['baseline', 'top', 'middle', 'bottom'],
	writingDirection: ['auto', 'ltr', 'rtl'],
};
